### ISSUE TITLE
KeyError on dungeon render

### ISSUE THREAD

**Issue by sshipway** [orphu/mcdungeon#256] opened 2014-09-18 23:53 UTC
This happens for me about one time in 20 or so, on dungeon render.  This is using the current dev snapshot.

```
Rendering features:   0%[>                                            ] TBDTrace
back (most recent call last):
  File "mcdungeon.py", line 1648, in <module>
    result = dungeon.generate(cache_path, __version__)
  File "D:\src\github\mcdungeon\dungeon.py", line 306, in generate
    self.renderfeatures()
  File "D:\src\github\mcdungeon\dungeon.py", line 1850, in renderfeatures
    x.render()
  File "D:\src\github\mcdungeon\features.py", line 915, in render
    while blocks[p + dl].material != materials.Air:
KeyError: (52,8,17)
```

I have not yet investigated in the source code.  This may be as a result of previously deleting some Dungeons and Treasure hunts in the world?

**Comment by dls314159** [comment] 2015-01-05 01:47
I think that I'm also seeing this error in a world that's just been generated using TerrainControl / WorldBorder prior to running mcdungeon.

If I understand what's up the thread, it doesn't seem likely that there are blank chunks in the area of the dungeon.

Would the output from the debug switch be useful?

**Comment by starg09** [comment] 2015-01-30 22:45
I'm having the same problem. And as in the comment above, it's a world generated with worldborder.

    ***** Placing dungeon 5 of 500 *****
    
    Searching for a suitable location...
    Map too wide for terminal: 997
    Dungeon size: 7 x 5 x 5
    Location:  (-3632,58,3344)
    Theme: elven
    Owner: Lord Glyn
    Generating rooms...
    Generating halls...
    Generating floors...
    Generating features...
    Generating ruins...
    Dungeon name: Tomb of Lord Glyn
    Finding secret rooms...
    Rendering ruins: 100%[===============================================>] 0:00:00
    Rendering rooms: 100%[===============================================>] 0:00:32
    Rendering halls: 100%[===============================================>] 0:00:01
    Rendering floors: 100%[==============================================>] 0:00:02
    Rendering features:  32%[==============>                              ] 0:00:02Traceback (most recent call last):
      File "mcdungeon.py", line 1640, in <module>
        result = dungeon.generate(cache_path, __version__)
      File "/mnt/disco2/mcdungeon-v0.14.1/dungeon.py", line 306, in generate
    self.renderfeatures()
      File "/mnt/disco2/mcdungeon-v0.14.1/dungeon.py", line 1850, in renderfeatures
    x.render()
      File "/mnt/disco2/mcdungeon-v0.14.1/features.py", line 915, in render
    while blocks[p + dl].material != materials.Air:
    KeyError: (107,20,17)
    
    [screen is terminating]

Config is hard mode, with maps enabled. Rooms are 4-8*4-8, with a 3-6 floor height.

**Comment by orphu** [comment] 2015-02-02 19:23
A reproducible case would help track this down. If someone could provide a map file along with config and output like starg09, that would help.

**Comment by starg09** [comment] 2015-02-05 12:41
@orphu I'd send you the map, but it's my Faction Server preloaded world... And it's almost 9GB in size, so I think not xD

At least it didn't leave glitched dungeons :D
And we spent 3 days, but filled it with over 300 of your dungeons. Thanks!

**Comment by bdwidhalm** [comment] 2015-03-26 04:37
@orphu I emailed you a map I got the error on, newly created nothing removed from map or added, default config and basic setting.  Actually second map only that I've used the tool so far, hope it helps.

**Comment by PsychoNavigator** [comment] 2015-03-31 13:19
In response to this comment:

https://github.com/orphu/mcdungeon/issues/256#issuecomment-86338366

The KeyError isn't anything to do with the coordinates. I'm not seeing any correlation with that at the moment.

My first thought was that maybe it's generating too many levels at too low a level when crashing, but I've found that's not consistent.

Currently working on a spreadsheet and tracking the the failures. I'd like to get a sample set of at least 10 before presenting it, maybe it will help.

**Comment by MikeyCarter** [comment] 2015-04-13 14:15
Any way of adding some code to mcdungeon to track the issue in more detail?   Like a crash log?   Just a thought.

**Comment by orphu** [comment] 2015-04-14 00:57
Hey so good news. I spent some time tonight with the map @bdwidhalm sent me, and I was able to repro it with v0.14.1. Working on a 0.14.2 repro. 

The problem is in the SecretRoom sometimes going nuts and trying to place a button outside the map in non-chunks. Pretty sure we saw this before right around the secret room rewrite, and I thought it was fixed, but it may have been reverted somewhere with all the crazy merges happening in 0.14.x.

**Comment by orphu** [comment] 2015-04-14 00:58
Oh, as a workaround, you can disable secret rooms in your config. Not great, I know, but since the bug is in the base SecretRoom class it affects all secret rooms.

**Comment by orphu** [comment] 2015-04-14 01:21
Map file (supplied by @bdwidhalm): [linky](https://drive.google.com/file/d/0B6TnX-hXKti2ejdtd1BES3RWSlE/view?usp=sharing)

A seed value that will generate a bad room:

```
./mcdungeon.py add keyerror 7-10 7-10 5-10 -s 26941
```

**Comment by orphu** [comment] 2015-04-15 03:32
I believe I have a fix for this, and I'm currently putting it through a large volume of random map generation to be sure.

Turns out it was actually caused by some of the recent diamond and alcove rooms added in 0.14.1 not playing nice with adjacent secret rooms. So, another work around would be to remove those two room types from your rooms list. 

But I'm going to let this generate rooms over night to see if I can come up with any more crashes. I think this is worth pushing out a new version for this, unless I can also squeeze in some fixes for the cache invalidation bugs @sshipway  found.

**Comment by orphu** [comment] 2015-04-15 03:35
Also, lol at my comments early in the thread. I already figured this out once. I'm starting to step away from this project for too long a period.

**Comment by orphu** [comment] 2015-04-15 13:23
I ran though a few thousand random dungeon iterations and this appears to be fixed.

**Comment by JiFish** [comment] 2015-04-15 14:59
Great news! I am sure a lot of people will be pleased about that.

**Closed** 2015-04-16 02:15 UTC
Labels: Bug Report, Confirmed Bug
