### ISSUE TITLE
Maps not generating

### ISSUE THREAD

**Issue by PsychoNavigator** [orphu/mcdungeon#297] opened 2015-04-18 05:04 UTC
My players are telling me that the level maps in dungeons aren't generating anything and appear to be blank. Any idea what may be the cause?

**Comment by JiFish** [comment] 2015-04-18 10:48
Are you using Multiworld / bukkit?

Please provide as much detail as you can.

**Comment by sshipway** [comment] 2015-04-18 21:56
Sounds as if the data/map_*.dat files are missing, or unreadable.  Is it possible that something you are doing copied only the region/r.*.*.mca files and omitted the other supporting files?  If the files are there, check sizes and permissions (if running your server under linux check file ownerships as well)

**Comment by orphu** [comment] 2015-04-22 15:44
I double checked map generation in 0.14.2 with the default config and it's working. Please provide us with more details about your setup as mentioned above.

**Comment by PsychoNavigator** [comment] 2015-04-30 23:53
Sorry, been away. Using spigot 1.8.3 w/ multiverse. I created a fresh world, used worldborder to gen the map, then run the script from another directory, pointing to that world folder. Nothing gets moved.

Both directories are under the same user. I'm going to attempt a new gen using the updated version anyway.

**Comment by JiFish** [comment] 2015-04-30 23:57
It sounds like you are not filling in the mapstore setting.

```
# mapstore will provide an alternate world in which to store your dungeon
# maps. If you're playing vanilla, don't worry about this. If you're using
# Bukkit with multiple worlds (like multiverse) set this to the name of your
# primary world. This can also be set on the command line, or in interactive
# mode. 
mapstore:
```

**Comment by PsychoNavigator** [comment] 2015-05-01 00:06
I recall getting an error when specifying the main world in the prompts something to the effect of it not being found. 

The world is not uniquely named, so it really didnt make sense to be getting that error. I'll re-run it and do a pastebin.

**Comment by PsychoNavigator** [comment] 2015-05-01 00:21
Here we go. Says it cannot find world data directory. Seems to be looking in the wrong place for that.

http://pastebin.com/W7SKi10e

**Comment by JiFish** [comment] 2015-05-01 00:25
Looks like a bug. I assume you have the configuration set to:

```
mapstore: world
```

**Comment by JiFish** [comment] 2015-05-01 00:31
I'll try to take a look at this at the weekend. Looks like the mapstore is not respecting the --dir option.

In the meantime, was a workaround, you could try moving the "world" folder to the location MCDungeon is attempting to use, and then move it back again after completion.

**Comment by PsychoNavigator** [comment] 2015-05-01 00:42
That is true. I will hold off, as my players aren't complaining too much at the moment. They accept that there will be bugs.

Thank you for looking into this.

**Comment by JiFish** [comment] 2015-05-01 00:51
You'll probably at least want to set the ```maps``` value to 0 and remove ```Custom Painting``` from the loot table. That will prevent the glitched maps from being generated, and save you some wasted map IDs.

**Comment by PsychoNavigator** [comment] 2015-05-01 00:58
I don't know anything about that, haha. I only gen the dungeons using the method shown. I'd like to figure out how to be able to run the script with everything preset rather than being prompted, but I couldn't process how to do that.

Needless to say with the script crashing often due to a bug I believe you guys have solved with the latest version, it was a challenge to do up some 400 dungeons. Well, not a challenge, just time consuming. Worth it either way though.

**Comment by JiFish** [comment] 2015-08-13 00:47
Apologies, @orphu, but I have come back to this after leaving it idle for ages and I'm a bit lost. The mapstore is a single world folder name, so at some point MCDungeon must be joining that with the save directory... but I can't seem to find it?! It's at that point the --dir option needs to be checked.

**Comment by orphu** [comment] 2015-08-13 01:42
AH yeah. [mcdungeon.py around line 420](https://github.com/orphu/mcdungeon/blob/master/mcdungeon.py#L420) in loadWorld(). 

Looks like it takes the mapstore path as an absolute path, and if that fails uses mclevel.saveFileDir to try and find the world. It should use the contents of --dir instead on that second try.

**Comment by orphu** [comment] 2015-08-13 01:48
Actually, maybe this is working as intended. The data dir should be specified as an absolute path, looks like maybe the reported used a sort path of just world/data. The fallback looks in the default minecraft directory for the platform. 

I think the fallback should just be removed and the data path needs to be absolute.

**Comment by PsychoNavigator** [comment] 2016-04-06 09:21
Hi again, I'm still having this problem with the latest version. I've been able to just skip defining the primary world  when prompted, but I'm wondering what effect it has on the world I'm genning dungeons in when i skip over it. What's missing, exactly?

**Comment by JoeFowlerJDi** [comment] 2016-04-06 09:24
Are you using Bukkit / Spigot & Multiverse?

**Comment by JiFish** [comment] 2016-04-06 09:25
Are you using Bukkit / Spigot & Multiverse?

**Comment by PsychoNavigator** [comment] 2016-04-06 09:25
Yes, I am.

**Comment by JiFish** [comment] 2016-04-06 09:30
You need to provide the name of the primary world when prompted because that's where all the maps are stored in this setup. This issue is due to the fact this prompt does not respect the --dir command-line option. So to work around it, copy both your primary world and the world that you want your dungeons in to your minecraft save folder and generate it there.

**Comment by PsychoNavigator** [comment] 2016-04-06 09:37
I don't have a minecraft save folder, I'm running this on a remote dedi box for my server.

**Comment by JiFish** [comment] 2016-04-06 09:45
Hmm, I wonder what pymclevel returns for mclevel.saveFileDir in that case. This is not a setup I have tried. You could try one of these workarounds:

- Make sure both worlds are in whatever directory MCDungeon is using by default without the --dir option. But I have no idea which directory this would be, or if this will work
- Copy the worlds somewhere you do have the minecraft save folder and run the process from there
- Do without maps and paintings. Remove them from your config with these instructions: https://github.com/orphu/mcdungeon/issues/297#issuecomment-98010544 You will still be prompted for the mapstore, but it won't be used.

**Comment by PsychoNavigator** [comment] 2016-04-06 09:50
On your first suggestion, that's possible, just makes that folder in particular a bit messy which is already the case, but would be fine!

Second one, if only. I get about 600kb upload speed from home, so by the time i've got the world loaded back up, 1.10 will have dropped!

Third one, when i just hit enter to skip, it gens dungeons with no issues, but the maps don't gen I think. 

I will experiment with your first suggestion to see if that helps. Thanks heaps, mate.

**Comment by JiFish** [comment] 2016-04-06 09:59
> but the maps don't gen I think. 

I'm pretty sure they should be. You'll probably be getting blank maps instead. You really should switch it off if you're not using it.

**Comment by PsychoNavigator** [comment] 2016-04-06 10:02
Yeah, sorry, blank maps they are. I'll just go head and remove them with the instructions as you suggest.

**Comment by JiFish** [comment] 2016-04-09 01:09
I've had another think about this, and I think the solution was staring me in the face all along. I've committed a fix that works for me if you'd like to try the development version.

**Comment by PsychoNavigator** [comment] 2016-04-21 00:57
I don't mind testing, how do I go about getting the dev version installed again?

**Comment by orphu** [comment] 2016-04-21 02:34
Theres a bit here about grabbing the dev version:

http://mcdungeon-docs.bubblemod.org/en/latest/downloading-running/

**Comment by orphu** [comment] 2016-05-04 00:41
This should now be in release if you want to test it there.

**Comment by JiFish** [comment] 2016-10-04 23:45
I'm going to assume this is fixed.

**Closed by JiFish** 2016-10-04 23:45 UTC
Labels: Confirmed Bug, Support
