### ISSUE TITLE
Having trouble genning dungeons, I am not sure what the problem is!

### ISSUE THREAD

**Issue by PsychoNavigator** [orphu/mcdungeon#420] opened 2017-08-07 07:52 UTC
I'm using development branch on a world pre-genned using 1.12 and WorldBorder to a 5000 block radius.

Dungeons do not want to generate.

https://pastebin.com/E02VzGhM

Please help. Thanks, gents.

**Comment by JiFish** [comment] 2017-08-07 08:17
> pre-genned using 1.12 and WorldBorder

Does that mean you are using `use_incomplete_chunks = true`. This is known to cause problems and is use-at-your-own-risk.

**Comment by PsychoNavigator** [comment] 2017-08-07 08:20
I have not tinkered with any settings and there should not be any incomplete chunks. I've kept my range inside of the worldborder and wb gens 20 chunks outside of that.

**Comment by PsychoNavigator** [comment] 2017-08-07 08:37
I can verify that the use incomplete chunks setting is in fact on false.

**Comment by PsychoNavigator** [comment] 2017-08-07 08:43
Running again using default option instead of hard with 20 maps, So far its laid 7 with no issues. I will attempt again  using hard_mode but i am beginning to suspect there may be an issue with the hard mode config at this point?

**Comment by JiFish** [comment] 2017-08-07 08:48
There is an bug with WorldBorder where it does not correctly mark chunks as complete. **Therefore you must set use_incomplete_chunks to be true**, or it will mark most of the whole map as unusable chunks.

This will likely cause other errors during generation. (The check is there for a reason and disabling it may cause crashes.) But it will at least generate dungeons. You can always resume generation after a crash.

Hard More will seem to be effected worse, but this is just because hard mode requires more area to generate dungeons. Even if the standard config works, you will note dungeons will not be generating in the area generated by WorldBorder.

There's no more we can do about this. The problem is at WorldBorder's end.

**Comment by PsychoNavigator** [comment] 2017-08-07 08:48
Cheers, I will go pester them! Thank you!

**Comment by JiFish** [comment] 2017-08-07 08:51
It might not be technically possible for them to solve this. I am not sure how it goes about generating new areas. There's some other discussion about this elsewhere in the issue queue. Setting use_incomplete_chunks to true will at least make it work.

**Comment by PsychoNavigator** [comment] 2017-08-07 08:56
True. At this point im going to just go experimental on this. Thank you. At least there's an answer to the issue, I reckon.

**Comment by JiFish** [comment] 2017-08-07 22:17
Closing this as solved by #354

Basically the options are: 1. Switch on `use_incomplete_chunks` and risk crashes or 2. Generate your map some other way

**Closed by JiFish** 2017-08-07 22:17 UTC
