### ISSUE TITLE
script crashing, how to fix?

### ISSUE THREAD

**Issue by PsychoNavigator** [orphu/mcdungeon#289] opened 2015-03-31 07:45 UTC
***** Placing dungeon 17 *****
     
    Searching for a suitable location...
    Map too wide for terminal: 296
    Dungeon size: 5 x 5 x 3
    Location:  (112,48,-320)
    Theme: norse
    Owner: Hojfruen Smundrnfr
    Generating rooms...
    Generating halls...
    Generating floors...
    Generating features...
    Generating ruins...
    Dungeon name: Barrow of Hojfruen Smundrnfr
    Finding secret rooms...
    Rendering ruins: 100%[===============================================>] 0:00:00
    Rendering rooms: 100%[===============================================>] 0:00:04
    Rendering halls: 100%[===============================================>] 0:00:00
    Rendering floors: 100%[==============================================>] 0:00:00
    Rendering features:   0%[>                                            ] TBDTraceback (most recent call last):
    File "./mcdungeon.py", line 1640, in <module> result = dungeon.generate(cache_path, __version__)
    File "/home/(redacted)/lab/mcdungeon/mcdungeon/dungeon.py", line 306, in generate self.renderfeatures()
    File "/home/(redacted)/lab/mcdungeon/mcdungeon/dungeon.py", line 1850, in renderfeatures x.render()
    File "/home/(redacted)/lab/mcdungeon/mcdungeon/features.py", line 915, in render while blocks[p + dl].material != materials.Air:
    KeyError: (14,8,11)

**Comment by JiFish** [comment] 2015-03-31 08:28
This is a duplicate of #256

**Closed by JiFish** 2015-03-31 08:28 UTC

**Comment by PsychoNavigator** [comment] 2015-03-31 09:29
Was issue #256 solved? I'm not seeing a solution to this.

**Comment by JiFish** [comment] 2015-03-31 09:56
This issue is very annoying, but it does not prevent use of MCDungeon. Any dungeons generated so far are still saved, so you just have to run again and pick up where you left off.

**Comment by PsychoNavigator** [comment] 2015-03-31 10:23
It's crashing on the next run on the first dungeon everytime though, I've been using interactive so it's a bit annyoing to re-enter everything. I'll try a manual config setup.

**Comment by JiFish** [comment] 2015-03-31 10:25
If you can figure out a region where this issue occurs 100% of the time, that might be useful information to post to issue #256.

**Comment by PsychoNavigator** [comment] 2015-03-31 10:27
Yeah I'm not sure. I don't even understand what the error means. I run it, it craps out. I don't see a constant in terms of where the problem comes up, but ill keep trying with it.
