### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by MikeyCarter** [orphu/mcdungeon#291] opened 2015-04-13 14:09 UTC
Every once and a while I get this error come up.

Rendering features:  77%[=================================>           ] 0:00:01Traceback (most recent call last):
  File "mcdungeon.py", line 1200, in <module>
    result = dungeon.generate(cache_path, __version__)
  File "/u2/cf-git/CarterFamily/MC_Addons/mcdungeon/dungeon.py", line 306, in generate
    self.renderfeatures()
  File "/u2/cf-git/CarterFamily/MC_Addons/mcdungeon/dungeon.py", line 1850, in renderfeatures
    x.render()
  File "/u2/cf-git/CarterFamily/MC_Addons/mcdungeon/features.py", line 915, in render
    while blocks[p + dl].material != materials.Air:
KeyError: (14,26,59)

Rerunning my script a second or third time and the problem goes away.  (some times it never comes up)   So must be some specific scenario created as mcdungeon is running.  Figured I should report it.

**Comment by JiFish** [comment] 2015-04-13 14:12
This is a duplicate of issue #256. If you do discover any more pertinent information it would be very useful if you'd post it over there.

**Closed by JiFish** 2015-04-13 14:12 UTC
