### ISSUE TITLE
Interactive mode cannot handle colour characters

### ISSUE THREAD

**Issue by sshipway** [orphu/mcdungeon#335] opened 2016-03-21 01:31 UTC
Some worlds downloaded from archive sites have names (and hence directory names) containing colour control characters -- eg,  `§4§kd§  Mountain Sky Village §4§kd§`

This gives an error in mcdungeon when running interactively:

```
    Traceback (most recent call last):
  File "D:\src\github\mcdungeon\mcdungeon.py", line 734, in <module>
    print '   ', file
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\xa7' in position 0: character maps to <undefined>
```

**Comment by JiFish** [comment] 2016-03-21 02:02
I think this is a duplicate of long-standing issue #85

**Comment by orphu** [comment] 2016-03-21 04:23
Hurm. Not the same issue. That's a tough one because python is throwing an error trying to print characters to your console that are not supported by your code page.

**Comment by JiFish** [comment] 2017-03-13 23:10
There may be ways to fix this by changing our output encoding. But since they they have to type the map name back in to mcdungeon anyway, I wonder if it wouldn't just be safer to exclude filenames that fail
`all(ord(char) < 128 for char in filename)`

That could be hostile towards foreign language users. I'm not sure how well we support this at the moment, anyway.

**Comment by mathuin** [comment] 2017-03-16 16:49
An alternative option would be to provide a list of directories on the screen and have the user select by number.  This doesn't scale well for command-line arguments, but that shouldn't be a problem.

```
Please select the world for which you wish to create a dungeon:
   1. AwesomeWorld
   2. UnicodeWorld
   3. NotMyCodePageWorld
```
You get the idea.

The `unicodedata` module apparently has a `normalize()` method which may be of assistance.

**Comment by JiFish** [comment] 2017-03-16 18:15
The reason I am hesitant to allow Unicode characters at all is we already know that some characters in paths cause [bigger issues than just outputting](https://github.com/orphu/mcdungeon/issues/85) that are likely never going to be fixed. Although we do know that the characters that cause this problem and that problem do not 100% overlap, my suspicion is fixing this will just move the problem in another place.

At the end of the day, it's not my call and the problem is not insurmountable. But this seems like a lot of effort for minimal benefit to me.

**Comment by orphu** [comment] 2017-03-22 00:44
I've often thought interactive mode should present things as lists more often instead of requiring someone to type things in. (largely unrelated to this issue)

**Closed** 2017-08-15 23:21 UTC
Labels: Bug Report, Confirmed Bug, Done
