### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by jtrent238** [orphu/mcdungeon#385] opened 2016-11-13 23:39 UTC
[LOG](https://gist.github.com/jtrent238/641f6bbfcca9a8c8af715860c69dcd02)

**Comment by orphu** [comment] 2016-11-14 02:02
This is a duplicate of #335 

Also, you're using a very old version of MCDungeon (like over three years old).  0.16 is the latest, and 0.17 will be out soon. 

You have a map name with non-ascii characters in it. You won't be able to use interactive mode. You should be able to manually add a dungeon to another map though. 

http://mcdungeon-docs.bubblemod.org/en/latest/downloading-running/#add-mode

**Closed** 2016-11-14 23:00 UTC
